### ISSUE TITLE
Python迭代器与生成器介绍及在Pytorch源码中应用 - 陈亮的博客 | Liang's Blog

### ISSUE THREAD

**Issue by chenllliang** [chenllliang/chenllliang.github.io#6]
https://chenllliang.github.io/2020/02/06/PyIter/ 

 面对我们的骨灰，高尚的人们将洒下热泪

**Comment by Tonybb9089** [comment]
class Fab(object):

   def __init__(self, max):
       self.max = max
       self.n, self.a, self.b = 0, 0, 1

   def __iter__(self):
       return self

   def next(self):
       if self.n < self.max:
           r = self.b
           self.a, self.b = self.b, self.a + self.b
           self.n = self.n + 1
           return r
       raise StopIteration()

这段代码在新的python3中是不对的，在新的迭代器规则中，迭代器对象应该实现__next__方法，而不是next。而新的内建函数next可以用于访问这个方法。
